name: watzl.it
favicon: null
layout_spectrum: 0.26754
typography_spectrum: 0.74549
title: Dominique Watzl
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75265990-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#000200'
    - '#c6d860'
    - '#183c00'
    - '#a59943'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
