typography_spectrum: 0.74549
color:
  brandColors:
    - '#fc8231'
    - '#6aa9fe'
    - '#47d9fe'
    - '#2b9ce7'
    - '#b2ea26'
  brandStrength: 0
  lightness: 1
  saturation: 0.875
  rhythmicContrast: 0
opengraph:
  image: null
  type: ''
  appId: null
layout_spectrum: 0.6731226025149226
analytics:
  google: UA-75265990-1
  facebook: null
  twitter: null
author:
  name: Dominique Watzl
  email: ''
name: watzl.it
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Altaussee
    id: 5d8e384a-1616-4bae-8bc7-55c749bbb175
    type: content
  - name: Who I am
    id: c027087f-2fed-47e3-a0aa-eed72086d79d
    type: content
  - name: Top Tens
    id: 9b438699-0337-4cbb-8135-1fe80b7b18b7
    type: content
favicon: null
title: Dominique Watzl
description: Photography
purpose: []
