name: watzl.it
favicon: null
layout_spectrum: 0.75632
typography_spectrum: 0.74549
title: Dominique Watzl
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75265990-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#fb6819'
    - '#8d4f64'
    - '#7b92be'
    - '#fba75e'
  brandStrength: 0
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
