name: watzl.it
favicon: null
layout_spectrum: 0.6731226025149226
typography_spectrum: 0.74549
author:
  name: Dominique Watzl
  email: ''
navigation: []
title: Dominique Watzl Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75265990-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: ''
  appId: null
color:
  brandColors:
    - '#F2385A'
    - '#F5A503'
    - '#E9F1DF'
    - '#4AD9D9'
    - '#36B1BF'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.875
  rhythmicContrast: 0.14126619487069547
purpose: []
