name: watzl.it
favicon: null
layout_spectrum: 0.6731226025149226
typography_spectrum: 0.74549
author:
  name: Dominique Watzl
  email: ''
title: Dominique Watzl
description: Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75265990-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: ''
  appId: null
color:
  brandColors:
    - '#fc8231'
    - '#6aa9fe'
    - '#47d9fe'
    - '#2b9ce7'
    - '#b2ea26'
  brandStrength: 0
  lightness: 1
  saturation: 0.875
  rhythmicContrast: 0
purpose: []
