typography_spectrum: 0.74549
color:
  brandColors:
    - '#F2385A'
    - '#F5A503'
    - '#E9F1DF'
    - '#4AD9D9'
    - '#36B1BF'
  brandStrength: 0.25533901364542544
  lightness: 0.7006643775384873
  saturation: 0.8452066299505532
  rhythmicContrast: 0.14126619487069547
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6731226025149226
analytics:
  google: UA-75265990-1
  facebook: null
  twitter: null
name: watzl.it
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - id: 5d8e384a-1616-4bae-8bc7-55c749bbb175
    url: 2016-07-17-altaussee.html
    name: Altaussee
    type: content
favicon: null
title: Dominique Watzl Photography
purpose: []
