name: Dominique Watzl
favicon: null
layout_spectrum: 1
typography_spectrum: 0.26409
title: test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75265990-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#fb6819'
    - '#8d4f64'
    - '#7b92be'
    - '#fba75e'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
