name: watzl.it
favicon: null
layout_spectrum: 0.26754
typography_spectrum: 0.74549
title: Dominique Watzl
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75265990-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfe9a'
    - '#f2bf6b'
    - '#d79e54'
    - '#bc8447'
    - '#99683b'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 1
purpose: []
