name: watzl.it
favicon: null
layout_spectrum: 0.6731226025149226
typography_spectrum: 0.74549
title: Dominique Watzl Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75265990-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F2385A'
    - '#F5A503'
    - '#E9F1DF'
    - '#4AD9D9'
    - '#36B1BF'
  brandStrength: 0.25533901364542544
  lightness: 0.7006643775384873
  saturation: 0.8452066299505532
  rhythmicContrast: 0.14126619487069547
purpose: []
